sudo: false
language: python
python:
  - "2.7"
install:
  - pip install pep8 coveralls
script:
  - pep8 --ignore=E501 src
  - coverage run --source=wowlint setup.py nosetests
after_success:
  coveralls
